// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleResponse struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_bcf1a291b70f3767, []int{0}
}
func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (dst *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(dst, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SimpleResponse) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Code                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Namespace            *Namespace            `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service              *Service              `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Instance             *Instance             `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_bcf1a291b70f3767, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() *wrappers.UInt32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Response) GetInfo() *wrappers.StringValue {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Response) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Response) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Response) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "v1.SimpleResponse")
	proto.RegisterType((*Response)(nil), "v1.Response")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_bcf1a291b70f3767) }

var fileDescriptor_response_bcf1a291b70f3767 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xe9, 0x8c, 0x5b, 0xcd, 0xdc, 0x18, 0x39, 0x85, 0x31, 0x44, 0x06, 0xc2, 0x40, 0xc8,
	0xdc, 0xf6, 0x2b, 0xb6, 0x83, 0x87, 0x14, 0xbd, 0x67, 0xf1, 0x5b, 0x09, 0x74, 0x49, 0x48, 0xd2,
	0xfa, 0xd7, 0x3d, 0x4a, 0xd2, 0x54, 0x4f, 0x5e, 0xbd, 0xbe, 0xef, 0xf3, 0xbc, 0x09, 0x1f, 0x9e,
	0x3b, 0xf0, 0xd6, 0x68, 0x0f, 0xcc, 0x3a, 0x13, 0x0c, 0x19, 0x75, 0xbb, 0xe5, 0x43, 0x6d, 0x4c,
	0xdd, 0xc0, 0x36, 0x25, 0xe7, 0xf6, 0xb2, 0xfd, 0x74, 0xc2, 0x5a, 0x70, 0xbe, 0x67, 0x96, 0x33,
	0x0f, 0xae, 0x53, 0x32, 0x2b, 0xeb, 0x80, 0xe7, 0x95, 0xba, 0xda, 0x06, 0x78, 0x9e, 0x22, 0x2f,
	0x18, 0x49, 0xf3, 0x01, 0xb4, 0x78, 0x2c, 0x36, 0xd3, 0xfd, 0x8a, 0xf5, 0x7b, 0x6c, 0xd8, 0x63,
	0x6f, 0x47, 0x1d, 0x0e, 0xfb, 0x77, 0xd1, 0xb4, 0xc0, 0x13, 0x19, 0x0d, 0xa5, 0x2f, 0x86, 0x8e,
	0xfe, 0x30, 0xaa, 0xe0, 0x94, 0xae, 0xb3, 0x11, 0xc9, 0xf5, 0x57, 0x81, 0xcb, 0xff, 0x7c, 0x90,
	0x3c, 0xe3, 0x3b, 0x2d, 0xae, 0xe0, 0xad, 0x90, 0x40, 0x51, 0xd2, 0x66, 0xac, 0xdb, 0xb1, 0xd7,
	0x21, 0xe4, 0xbf, 0x3d, 0x79, 0xc2, 0x93, 0x7c, 0x24, 0x7a, 0x9b, 0xd0, 0x69, 0x44, 0xab, 0x3e,
	0xe2, 0x43, 0x47, 0x36, 0xb8, 0x54, 0xda, 0x07, 0xa1, 0x25, 0xd0, 0x71, 0xe2, 0xee, 0x23, 0x77,
	0xcc, 0x19, 0xff, 0x69, 0x4f, 0xa8, 0xbc, 0x59, 0xa0, 0x13, 0x2a, 0x27, 0x8b, 0xd5, 0x79, 0x9c,
	0x7e, 0x79, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x74, 0x81, 0xa2, 0xe6, 0xbc, 0x01, 0x00, 0x00,
}
